version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bettracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bettracker_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bettracker_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bettracker_user -d bettracker_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bettracker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
